### ISSUE TITLE
GDC dev container name converts dash to underscore

### ISSUE THREAD

**Issue by k-chainalysis** [devxpod/GDC#7]
### Expected
When launching GDC development container, the name of the container is the name of the project, with suffix `-dev-1` appended

### Actual
Almost as expected, except that a dash in the project name is converted to an underscore

### Example
* project name: `my-project`
* generated dev container name: `my_project-dev-1`

**Comment by paulrobello** [comment]
This is by design. 
Docker Compose automatically appends the service name "dev" and instance num "1" using hyphens, hence the "-dev-1".
To make it easier to see / parse the GDC name portion of the compose project name all spaces and hyphens are converted to underscore.
I believe having hyphens in the name other than those automatically added by compose caused problems with older versions of compose as well.

**Comment by k-chainalysis** [comment]
Ah, thanks for the explanation! Very cool project.
